CREATE OR REPLACE PACKAGE BODY PROGRESS_LOGS_PKG AS
   PROCEDURE LOG(
      LOG_DATE DATE,
      LOG_SOURCE VARCHAR2,
      LOG_LABEL VARCHAR2,
      LOG_TEXT VARCHAR2
   ) AS
   BEGIN
      INSERT INTO PROGRESS_LOGS (LOG_DATE, LOG_SOURCE, LOG_LABEL, LOG_TEXT)
      VALUES( LOG_DATE, LOG_SOURCE, LOG_LABEL, LOG_TEXT);
   END LOG;
END PROGRESS_LOGS_PKG;
